#!/usr/bin/env python3
"""Local FortisAI Composio MCP proxy.

This service gives FortisAI a stable local HTTP MCP endpoint even when the
actual Composio MCP session URL is generated by the Composio SDK or stored in
Vault. It intentionally returns configuration status without exposing secrets.
"""

from __future__ import annotations

import json
import os
import threading
from typing import Any, Dict, Optional

import requests
from fastapi import FastAPI, HTTPException, Request

APP = FastAPI(title="fortisai-composio-local-mcp-proxy", version="1.0.0")

COMPOSIO_API_KEY = os.getenv("COMPOSIO_API_KEY", "").strip()
COMPOSIO_UPSTREAM_MCP_URL = os.getenv("COMPOSIO_UPSTREAM_MCP_URL", "").strip()
COMPOSIO_MCP_HEADERS_JSON = os.getenv("COMPOSIO_MCP_HEADERS_JSON", "").strip()
COMPOSIO_USER_ID = os.getenv("COMPOSIO_USER_ID", "fortisai-openwebui").strip()
COMPOSIO_TOOLKITS = [item.strip() for item in os.getenv("COMPOSIO_TOOLKITS", "").split(",") if item.strip()]
COMPOSIO_SESSION_ID = os.getenv("COMPOSIO_SESSION_ID", "").strip()
VAULT_ADDR = os.getenv("FORTISAI_VAULT_ADDR") or os.getenv("VAULT_ADDR") or ""
VAULT_TOKEN = os.getenv("VAULT_TOKEN", "").strip()

_SESSION_LOCK = threading.Lock()
_SESSION_CACHE: Dict[str, Dict[str, Any]] = {}
_LAST_ERROR = ""


def _vault_read(path: str) -> Optional[str]:
    if not VAULT_ADDR or not VAULT_TOKEN:
        return None
    url = f"{VAULT_ADDR.rstrip('/')}/v1/secret/data/fortisai/dev/{path.strip('/')}"
    try:
        response = requests.get(url, headers={"X-Vault-Token": VAULT_TOKEN}, timeout=8)
        if response.status_code == 404:
            return None
        response.raise_for_status()
        data = response.json().get("data", {}).get("data", {})
        value = data.get("value")
        if value is None and len(data) == 1:
            value = next(iter(data.values()))
        return str(value) if value is not None else None
    except Exception:
        return None


def _configured_api_key() -> str:
    return COMPOSIO_API_KEY or _vault_read("composio/api_key") or ""


def _clean_user_id(value: Any) -> str:
    text = str(value or "").strip()
    if not text:
        return ""
    return "".join(ch if ch.isalnum() or ch in "@._:-" else "_" for ch in text)[:160]


def _configured_user_id(openwebui_user_id: str = "") -> str:
    return _clean_user_id(openwebui_user_id) or _vault_read("composio/user_id") or COMPOSIO_USER_ID or "fortisai-openwebui"


def _header_value(request: Request, *names: str) -> str:
    for name in names:
        value = request.headers.get(name)
        if value:
            return value.strip()
    return ""


def _user_from_payload(payload: Any) -> str:
    if not isinstance(payload, dict):
        return ""
    params = payload.get("params") if isinstance(payload.get("params"), dict) else {}
    candidates = [
        params.get("_fortisai_openwebui_user_id"),
        params.get("openwebui_user_id"),
        params.get("openwebui_username"),
        params.get("user_id"),
        params.get("username"),
        payload.get("openwebui_user_id"),
        payload.get("user_id"),
    ]
    for candidate in candidates:
        cleaned = _clean_user_id(candidate)
        if cleaned:
            return cleaned
    return ""


def _extract_openwebui_user(request: Request, payload: Any = None) -> str:
    return _configured_user_id(
        _user_from_payload(payload)
        or _header_value(request, "x-fortisai-openwebui-user", "x-openwebui-user-id", "x-openwebui-user-email", "x-openwebui-user-name", "x-user-id")
    )


def _scrub_fortisai_params(payload: Any) -> Any:
    if isinstance(payload, dict) and isinstance(payload.get("params"), dict):
        payload = dict(payload)
        params = dict(payload["params"])
        for key in ["_fortisai_openwebui_user_id", "openwebui_user_id", "openwebui_username", "user_id", "username"]:
            params.pop(key, None)
        payload["params"] = params
    return payload


def _configured_toolkits() -> list[str]:
    raw = _vault_read("composio/toolkits")
    if raw:
        return [item.strip() for item in raw.split(",") if item.strip()]
    return COMPOSIO_TOOLKITS


def _headers_from_json(raw: str) -> Dict[str, str]:
    if not raw:
        return {}
    try:
        parsed = json.loads(raw)
        if isinstance(parsed, dict):
            return {str(k): str(v) for k, v in parsed.items()}
    except json.JSONDecodeError:
        return {}
    return {}


def _configured_upstream() -> tuple[str, Dict[str, str], str]:
    url = COMPOSIO_UPSTREAM_MCP_URL or _vault_read("composio/upstream_mcp_url") or _vault_read("composio/mcp_url") or ""
    headers = _headers_from_json(COMPOSIO_MCP_HEADERS_JSON or _vault_read("composio/mcp_headers_json") or "")
    return url, headers, "vault_or_env" if url else ""


def _session_mcp_from_sdk(openwebui_user_id: str = "") -> tuple[str, Dict[str, str], str]:
    global _LAST_ERROR
    api_key = _configured_api_key()
    user_id = _configured_user_id(openwebui_user_id)
    with _SESSION_LOCK:
        cached = _SESSION_CACHE.get(user_id) or {}
        if cached.get("url"):
            return cached["url"], dict(cached.get("headers") or {}), "sdk_cached"
        try:
            from composio import Composio  # type: ignore
        except Exception as exc:
            _LAST_ERROR = f"Composio SDK import failed: {exc}"
            return "", {}, ""
        try:
            if api_key:
                try:
                    client = Composio(api_key=api_key)
                except TypeError:
                    os.environ.setdefault("COMPOSIO_API_KEY", api_key)
                    client = Composio()
            else:
                client = Composio()
            toolkits = _configured_toolkits()
            kwargs: Dict[str, Any] = {"mcp": True}
            if toolkits:
                kwargs["toolkits"] = toolkits
            if COMPOSIO_SESSION_ID:
                session = client.use(COMPOSIO_SESSION_ID, **kwargs)
            else:
                session = client.create(user_id=user_id, **kwargs)
            mcp = getattr(session, "mcp", None)
            url = getattr(mcp, "url", None) or (mcp.get("url") if isinstance(mcp, dict) else None)
            headers = getattr(mcp, "headers", None) or (mcp.get("headers") if isinstance(mcp, dict) else None) or {}
            if not url:
                _LAST_ERROR = "Composio SDK session did not return an MCP URL."
                return "", {}, ""
            _SESSION_CACHE[user_id] = {"url": str(url), "headers": {str(k): str(v) for k, v in dict(headers).items()}}
            _LAST_ERROR = ""
            return _SESSION_CACHE[user_id]["url"], dict(_SESSION_CACHE[user_id]["headers"]), "sdk_session"
        except Exception as exc:
            _LAST_ERROR = f"Composio SDK session creation failed: {exc}"
            return "", {}, ""


def _resolved_mcp_target(openwebui_user_id: str = "") -> tuple[str, Dict[str, str], str]:
    url, headers, source = _configured_upstream()
    if url:
        return url, headers, source
    return _session_mcp_from_sdk(openwebui_user_id)


@APP.get("/healthz")
def healthz() -> Dict[str, Any]:
    return {"ok": True}


@APP.get("/connection_info")
def connection_info(request: Request) -> Dict[str, Any]:
    openwebui_user_id = _extract_openwebui_user(request)
    url, headers, source = _resolved_mcp_target(openwebui_user_id)
    return {
        "ok": True,
        "has_api_key": bool(_configured_api_key()),
        "uses_local_composio_auth": not bool(_configured_api_key()) and not bool(_configured_upstream()[0]),
        "has_mcp_url": bool(url),
        "mcp_source": source,
        "has_headers": bool(headers),
        "user_id": openwebui_user_id,
        "session_cache_users": sorted(_SESSION_CACHE.keys()),
        "toolkits": _configured_toolkits(),
        "last_error": _LAST_ERROR,
    }


@APP.post("/mcp")
async def mcp(request: Request) -> Any:
    payload = await request.json()
    openwebui_user_id = _extract_openwebui_user(request, payload)
    url, headers, source = _resolved_mcp_target(openwebui_user_id)
    if not url:
        raise HTTPException(status_code=503, detail=_LAST_ERROR or "Composio MCP target is not configured.")
    payload = _scrub_fortisai_params(payload)
    merged_headers = {"Content-Type": "application/json", **headers}
    try:
        response = requests.post(url, headers=merged_headers, json=payload, timeout=120)
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Composio MCP upstream request failed via {source}: {exc}") from exc
    try:
        body = response.json()
    except Exception:
        body = {"raw": response.text[:4000]}
    if response.status_code >= 400:
        raise HTTPException(status_code=response.status_code, detail=body)
    return body


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(APP, host="0.0.0.0", port=int(os.getenv("COMPOSIO_LOCAL_PORT", "8090")))
